server:
  port: 8085
spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shubham4898/microServiceConfiguration
          clone-on-start: true



